// Database types for Supabase - Guru Spenturi v2
// These types should be generated by Supabase CLI in production

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type role_enum = 'superadmin' | 'admin' | 'urusan' | 'guru' | 'siswa'
export type status_enum = 'aktif' | 'nonaktif'
export type status_siswa_enum = 'aktif' | 'nonaktif' | 'alumni'
export type status_pegawai_enum = 'PNS' | 'PPPK' | 'PPPK PW' | 'GTT'

// Extended types with relations
export interface SiswaWithRelations {
  id: string
  nis: string
  nisn: string | null
  nipd: string | null
  nama: string
  jenjang: number | null
  jenis_kelamin: jenis_kelamin_enum
  status_siswa: status_siswa_enum
  tahun_lulus: number | null
  pengguna_id: string | null
  created_at: string
  updated_at: string
  kelas_dapo?: { id: string; nama: string } | null
  kelas_real?: { id: string; nama: string } | null
}

export interface GuruWithRelations {
  id: string
  kode_guru: string
  urutan: number | null
  nama: string
  status_pegawai: status_pegawai_enum
  nip: string
  status: status_enum
  pengguna_id: string | null
  created_at: string
  updated_at: string
  pengguna?: { nama: string } | null
}
export type mode_penilaian_enum = 'pts' | 'semester'
export type mode_ttd_enum = 'digital' | 'basah'
export type jenis_kelamin_enum = 'L' | 'P'
export type acuan_kelas_enum = 'real' | 'dapo'
export type jam_ujian_enum = 'Jam ke - 1' | 'Jam ke - 2'
export type status_backup_enum = 'sukses' | 'gagal'
export type tugas_tambahan_enum = 'kepala_kurikulum' | 'koordinator_7' | 'koordinator_8' | 'koordinator_9' | 'wali_kelas'
export type jenis_ujian_enum = 'Asesmen Sumatif Tengah Semester' | 'Asesmen Sumatif Akhir Semester' | 'Asesmen Sumatif Akhir Tahun' | 'Asesmen Sumatif Akhir Jenjang'
export type hari_enum = 'Senin' | 'Selasa' | 'Rabu' | 'Kamis' | 'Jumat' | 'Sabtu'

export interface Database {
  public: {
    Tables: {
      pengguna: {
        Row: {
          id: string
          username: string
          nama: string
          role: role_enum
          status: status_enum
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          nama: string
          role: role_enum
          status?: status_enum
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          nama?: string
          role?: role_enum
          status?: status_enum
          created_at?: string
          updated_at?: string
        }
      }
      tahun_pelajaran: {
        Row: {
          id: string
          nama: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          nama: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          nama?: string
          created_at?: string
          updated_at?: string
        }
      }
      semester: {
        Row: {
          id: string
          tahun_pelajaran_id: string
          nama: string
          status: status_enum
          mode_penilaian: mode_penilaian_enum
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tahun_pelajaran_id: string
          nama: string
          status?: status_enum
          mode_penilaian?: mode_penilaian_enum
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tahun_pelajaran_id?: string
          nama?: string
          status?: status_enum
          mode_penilaian?: mode_penilaian_enum
          created_at?: string
          updated_at?: string
        }
      }
      guru: {
        Row: {
          id: string
          kode_guru: string
          urutan: number | null
          nama: string
          status_pegawai: status_pegawai_enum
          nip: string
          status: status_enum
          pengguna_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          kode_guru: string
          urutan?: number | null
          nama: string
          status_pegawai: status_pegawai_enum
          nip?: string
          status?: status_enum
          pengguna_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          kode_guru?: string
          urutan?: number | null
          nama?: string
          status_pegawai?: status_pegawai_enum
          nip?: string
          status?: status_enum
          pengguna_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      siswa: {
        Row: {
          id: string
          nis: string
          nisn: string | null
          nipd: string | null
          nama: string
          jenjang: number | null
          jenis_kelamin: jenis_kelamin_enum
          status_siswa: status_siswa_enum
          tahun_lulus: number | null
          pengguna_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          nis: string
          nisn?: string | null
          nipd?: string | null
          nama: string
          jenjang?: number | null
          jenis_kelamin: jenis_kelamin_enum
          status_siswa?: status_siswa_enum
          tahun_lulus?: number | null
          pengguna_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          nis?: string
          nisn?: string | null
          nipd?: string | null
          nama?: string
          jenjang?: number | null
          jenis_kelamin?: jenis_kelamin_enum
          status_siswa?: status_siswa_enum
          tahun_lulus?: number | null
          pengguna_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      kelas_dapo: {
        Row: {
          id: string
          semester_id: string
          nama: string
          jenjang: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          semester_id: string
          nama: string
          jenjang: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          semester_id?: string
          nama?: string
          jenjang?: number
          created_at?: string
          updated_at?: string
        }
      }
      kelas_real: {
        Row: {
          id: string
          semester_id: string
          nama: string
          jenjang: number
          ruang: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          semester_id: string
          nama: string
          jenjang: number
          ruang?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          semester_id?: string
          nama?: string
          jenjang?: number
          ruang?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      siswa_kelas: {
        Row: {
          id: string
          siswa_id: string
          semester_id: string
          kelas_dapo_id: string | null
          kelas_real_id: string | null
          jenjang: number | null
          is_titipan: boolean
          nomor_absen_dapo: number | null
          nomor_absen_real: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          siswa_id: string
          semester_id: string
          kelas_dapo_id?: string | null
          kelas_real_id?: string | null
          jenjang?: number | null
          is_titipan?: boolean
          nomor_absen_dapo?: number | null
          nomor_absen_real?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          siswa_id?: string
          semester_id?: string
          kelas_dapo_id?: string | null
          kelas_real_id?: string | null
          jenjang?: number | null
          is_titipan?: boolean
          nomor_absen_dapo?: number | null
          nomor_absen_real?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      mata_pelajaran: {
        Row: {
          id: string
          kode_mapel: string
          nama: string
          kelompok: string | null
          agama: string | null
          status: status_enum
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          kode_mapel: string
          nama: string
          kelompok?: string | null
          agama?: string | null
          status?: status_enum
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          kode_mapel?: string
          nama?: string
          kelompok?: string | null
          agama?: string | null
          status?: status_enum
          created_at?: string
          updated_at?: string
        }
      }
      kepala_sekolah: {
        Row: {
          id: string
          nama: string
          nip: string
          tanda_tangan_url: string | null
          status: status_enum
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          nama: string
          nip: string
          tanda_tangan_url?: string | null
          status?: status_enum
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          nama?: string
          nip?: string
          tanda_tangan_url?: string | null
          status?: status_enum
          created_at?: string
          updated_at?: string
        }
      }
      tugas_tambahan: {
        Row: {
          id: string
          pengguna_id: string
          semester_id: string
          jenis: tugas_tambahan_enum
          kelas_real_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pengguna_id: string
          semester_id: string
          jenis: tugas_tambahan_enum
          kelas_real_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          pengguna_id?: string
          semester_id?: string
          jenis?: tugas_tambahan_enum
          kelas_real_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add more tables as needed...
    }
    Views: {}
    Functions: {}
    Enums: {
      role_enum: role_enum
      status_enum: status_enum
      status_siswa_enum: status_siswa_enum
      status_pegawai_enum: status_pegawai_enum
      mode_penilaian_enum: mode_penilaian_enum
      mode_ttd_enum: mode_ttd_enum
      jenis_kelamin_enum: jenis_kelamin_enum
      acuan_kelas_enum: acuan_kelas_enum
      jam_ujian_enum: jam_ujian_enum
      status_backup_enum: status_backup_enum
      tugas_tambahan_enum: tugas_tambahan_enum
      jenis_ujian_enum: jenis_ujian_enum
      hari_enum: hari_enum
    }
  }
}
